version: '3.4'

services:
  modsentesttask:
    image: ${DOCKER_REGISTRY-}modsentesttask
    build:
      context: .
      dockerfile: ModsenTestTask/Dockerfile
  
  postgres_db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: BookShop
      #POSTGRES_HOST: 127.0.0.1
    volumes:
      - postgres-data:/var/lib/postgresql/data     
    ports:
      - "5432:5432"
    #networks:
    #  - "webapi"
    restart: always

volumes:
  postgres-data:
